"""Technical regulatory screening and formal deficiency schemas for InterconnectAI."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class ScreenId(StrEnum):
    """Standardized technical screens defined in California Rule 21 & IEEE 1547."""

    SCREEN_A_APPLICABILITY = "SCREEN_A_APPLICABILITY"
    SCREEN_B_CERTIFIED_EQUIPMENT = "SCREEN_B_CERTIFIED_EQUIPMENT"
    SCREEN_C_VOLTAGE_DROP = "SCREEN_C_VOLTAGE_DROP"
    SCREEN_D_PENETRATION_15PCT = "SCREEN_D_PENETRATION_15PCT"
    SCREEN_E_SHORT_CIRCUIT_DUTY = "SCREEN_E_SHORT_CIRCUIT_DUTY"
    SCREEN_F_SHORT_CIRCUIT_RATIO = "SCREEN_F_SHORT_CIRCUIT_RATIO"
    SCREEN_H_DISCONNECT_SWITCH = "SCREEN_H_DISCONNECT_SWITCH"
    SCREEN_I_ANTI_ISLANDING = "SCREEN_I_ANTI_ISLANDING"


class ScreenStatus(StrEnum):
    """Evaluation outcome for an individual engineering screen."""

    PASS = "PASS"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    REQUIRES_SUPPLEMENTAL_REVIEW = "REQUIRES_SUPPLEMENTAL_REVIEW"


class OverallOutcome(StrEnum):
    """Aggregate regulatory determination for an interconnection application."""

    FAST_TRACK_APPROVED = "FAST_TRACK_APPROVED"
    DEFICIENCY_ISSUED = "DEFICIENCY_ISSUED"
    SUPPLEMENTAL_REVIEW_REQUIRED = "SUPPLEMENTAL_REVIEW_REQUIRED"


class ScreenResult(BaseModel):
    """Deterministic evaluation outcome for an individual engineering screen."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    screen_id: ScreenId = Field(..., description="Unique technical screen identifier")
    screen_name: str = Field(..., description="Human-readable title of the screen")
    status: ScreenStatus = Field(..., description="Pass/Fail determination")
    calculated_value: float | str | None = Field(
        default=None, description="Deterministic numeric or categorical result from calculation"
    )
    threshold_value: float | str | None = Field(
        default=None, description="Regulatory threshold criteria from tariff handbook"
    )
    citation: str = Field(..., description="Exact legal/regulatory tariff section reference")
    reasoning: str = Field(..., description="Technical engineering justification explaining result")
    requires_human_override: bool = Field(
        default=False,
        description="Flag indicating engineer review or visual verification is needed",
    )


class DeficiencyItem(BaseModel):
    """Formally structured deficiency notice item requiring applicant cure."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    code: str = Field(
        ..., description="Standardized deficiency error code (e.g. DEF_PENETRATION_EXCEEDED)"
    )
    title: str = Field(..., description="Short summary title of the non-conformance")
    description: str = Field(
        ..., description="Detailed explanation of the technical or exhibit deficiency"
    )
    violating_screen: ScreenId = Field(
        ..., description="The specific screen that triggered this deficiency"
    )
    required_cure_action: str = Field(
        ..., description="Specific corrective action the applicant must perform to cure"
    )
    cure_deadline_business_days: int = Field(
        default=10,
        ge=1,
        description="Statutory deadline to submit cure before application withdrawal",
    )
    tariff_citation: str = Field(
        ..., description="Exact regulatory standard clause mandating this requirement"
    )


class ScreeningReport(BaseModel):
    """Complete technical review memo generated by the InterconnectAI screening agent."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    application_id: str = Field(..., description="Target application identifier")
    overall_outcome: OverallOutcome = Field(..., description="Final regulatory determination")
    screens: list[ScreenResult] = Field(
        ..., min_length=1, description="Results of all evaluated screens"
    )
    deficiencies: list[DeficiencyItem] = Field(
        default_factory=list, description="List of formal deficiency items (empty if approved)"
    )
    aggregate_generation_kw: float = Field(
        ..., ge=0, description="Total active generating capacity evaluated (kW)"
    )
    feeder_penetration_pct: float | None = Field(
        default=None, ge=0, description="Calculated feeder penetration percentage (%)"
    )
    engineer_sign_off_required: bool = Field(
        default=True, description="Enforces human engineer review before dispatching report"
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Timestamp of report generation",
    )

    @property
    def has_deficiencies(self) -> bool:
        """Return True if any deficiency items were recorded."""
        return len(self.deficiencies) > 0

    @property
    def passed_screens_count(self) -> int:
        """Count of screens with PASS status."""
        return sum(1 for s in self.screens if s.status == ScreenStatus.PASS)

    @property
    def failed_screens_count(self) -> int:
        """Count of screens with FAIL status."""
        return sum(1 for s in self.screens if s.status == ScreenStatus.FAIL)
